name: CI Checks
on: 
  push:
  pull_request:

jobs:
  idl-submodule-points-to-master:
    name: IDL submodule points to master
    runs-on: ubuntu-latest # uses ubuntu as runner
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # ensures git submodules are intialized and updated
          fetch-depth: 0 # get full history for branch checking

      - name: Check IDL submodule status (must point to master)
        run: make .idl-status

  golang-integration-test-with-sqlite:
    name: Golang integration test with sqlite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Run integration profile for sqlite
        uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          timeout_minutes: 30
          command: |
            docker compose -f docker/github_actions/docker-compose.yml run integration-test-sqlite bash -c "make cover_integration_profile"

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: go-sqlite-integration-coverage
          path: .build/coverage/*.out
